AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

EXTRAFLAGS += -flto
