# SRC += lukexor.c

CAPS_WORD_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
TRI_LAYER_ENABLE = yes

# Reduces firmware size
AUTO_SHIFT_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
