SRC += config.c

CAPS_WORD_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio and system control
LAYER_LOCK_ENABLE = yes

# Reduces firmware size
AUTO_SHIFT_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
